# Generated by Django 6.0.6 on 2026-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Obligatoria; se muestra en tus resultados.', null=True, upload_to='fotos/', verbose_name='fotografía'),
        ),
    ]
