# Generated by Django 6.0.6 on 2026-06-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Si está activo, se obliga a crear una nueva contraseña al ingresar.', verbose_name='debe cambiar contraseña'),
        ),
    ]
