# Generated by Django 6.0.6 on 2026-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_mime',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
