# Generated by Django 6.0.6 on 2026-06-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_photo_data_user_photo_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='eliminado el'),
        ),
    ]
