# Generated by Django 6.0.7 on 2026-07-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_thumb_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
