# Generated by Django 6.0.6 on 2026-10-07 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_photo_thumb_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='lead directo'),
        ),
    ]
