# Generated by Django 6.0.7 on 2026-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_seed_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('REQUIERE_AJUSTES', 'Requiere ajustes'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('AUTORIZADA', 'En progreso'), ('COMPLETADA', 'Completado · por validar'), ('VALIDADA', 'Completado'), ('NO_CONCLUIDA', 'No concluido')], default='BORRADOR', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='historicalcourserequest',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('REQUIERE_AJUSTES', 'Requiere ajustes'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('AUTORIZADA', 'En progreso'), ('COMPLETADA', 'Completado · por validar'), ('VALIDADA', 'Completado'), ('NO_CONCLUIDA', 'No concluido')], default='BORRADOR', max_length=16, verbose_name='estado'),
        ),
    ]
