# Generated by Django 6.0.6 on 2026-06-10 15:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArenaImpactScore',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='calificación')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='actualizado el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('captured_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='capturado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'historical Impacto Arena',
                'verbose_name_plural': 'historical Impactos Arena',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOwnershipEvaluation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada')], default='BORRADOR', max_length=10, verbose_name='estado')),
                ('strengths', models.TextField(blank=True, verbose_name='fortalezas')),
                ('opportunities', models.TextField(blank=True, verbose_name='oportunidades')),
                ('comments', models.TextField(blank=True, verbose_name='comentarios')),
                ('confirmed_with_leader', models.BooleanField(default=False, verbose_name='confirmada con el líder')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='calificación')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada el')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='actualizada el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.project', verbose_name='proyecto')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questionnaires.questionnairetemplate', verbose_name='cuestionario (versión)')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
                ('validator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='líder validador')),
            ],
            options={
                'verbose_name': 'historical evaluación de Ownership',
                'verbose_name_plural': 'historical evaluaciones de Ownership',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalValueDeliveryEvaluation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_VALIDACION', 'En validación'), ('VALIDADA', 'Validada')], default='BORRADOR', max_length=14, verbose_name='estado')),
                ('client_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='satisfacción del cliente')),
                ('deliverables', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='entregables')),
                ('time_finite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tiempo (finito)')),
                ('time_indefinite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tiempo (indefinido)')),
                ('rejection_comment', models.TextField(blank=True, verbose_name='comentario de rechazo')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='calificación')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validada el')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='actualizada el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('evaluator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='líder evaluador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.project', verbose_name='proyecto')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validado por (director)')),
            ],
            options={
                'verbose_name': 'historical evaluación de Entrega de Valor',
                'verbose_name_plural': 'historical evaluaciones de Entrega de Valor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OwnershipEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada')], default='BORRADOR', max_length=10, verbose_name='estado')),
                ('strengths', models.TextField(blank=True, verbose_name='fortalezas')),
                ('opportunities', models.TextField(blank=True, verbose_name='oportunidades')),
                ('comments', models.TextField(blank=True, verbose_name='comentarios')),
                ('confirmed_with_leader', models.BooleanField(default=False, verbose_name='confirmada con el líder')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='calificación')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_evaluations', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_evaluations', to='catalog.project', verbose_name='proyecto')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_evaluations', to='questionnaires.questionnairetemplate', verbose_name='cuestionario (versión)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_validations', to=settings.AUTH_USER_MODEL, verbose_name='líder validador')),
            ],
            options={
                'verbose_name': 'evaluación de Ownership',
                'verbose_name_plural': 'evaluaciones de Ownership',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='valor')),
                ('is_na', models.BooleanField(default=False, verbose_name='no aplica')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_answers', to='questionnaires.question', verbose_name='pregunta')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.ownershipevaluation', verbose_name='evaluación')),
            ],
            options={
                'verbose_name': 'respuesta de Ownership',
                'verbose_name_plural': 'respuestas de Ownership',
            },
        ),
        migrations.CreateModel(
            name='ValueDeliveryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_VALIDACION', 'En validación'), ('VALIDADA', 'Validada')], default='BORRADOR', max_length=14, verbose_name='estado')),
                ('client_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='satisfacción del cliente')),
                ('deliverables', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='entregables')),
                ('time_finite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tiempo (finito)')),
                ('time_indefinite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tiempo (indefinido)')),
                ('rejection_comment', models.TextField(blank=True, verbose_name='comentario de rechazo')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='calificación')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vd_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='líder evaluador')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_deliveries', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_deliveries', to='catalog.project', verbose_name='proyecto')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vd_validations', to=settings.AUTH_USER_MODEL, verbose_name='validado por (director)')),
            ],
            options={
                'verbose_name': 'evaluación de Entrega de Valor',
                'verbose_name_plural': 'evaluaciones de Entrega de Valor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaImpactScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='calificación')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captured_impacts', to=settings.AUTH_USER_MODEL, verbose_name='capturado por')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arena_impacts', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_impacts', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'Impacto Arena',
                'verbose_name_plural': 'Impactos Arena',
                'constraints': [models.UniqueConstraint(fields=('user', 'period'), name='unique_arena_impact')],
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('value_delivery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('arena_impact_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('band', models.CharField(blank=True, max_length=20, verbose_name='banda')),
                ('is_complete', models.BooleanField(default=False, verbose_name='completa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_scores', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'calificación final',
                'verbose_name_plural': 'calificaciones finales',
                'constraints': [models.UniqueConstraint(fields=('user', 'period'), name='unique_final_score')],
            },
        ),
        migrations.AddConstraint(
            model_name='ownershipevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'project', 'period'), name='unique_ownership_eval'),
        ),
        migrations.AddConstraint(
            model_name='ownershipanswer',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question'), name='unique_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='valuedeliveryevaluation',
            constraint=models.UniqueConstraint(fields=('project', 'period'), name='unique_vd_eval'),
        ),
    ]
