# Generated by Django 6.0.6 on 2026-06-23 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_project_rename_lead_to_owner'),
        ('evaluations', '0002_ownershipevaluator'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ownershipevaluation',
            name='unique_ownership_eval',
        ),
        migrations.AlterField(
            model_name='ownershipevaluation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_evaluations', to='catalog.project', verbose_name='proyecto'),
        ),
        migrations.AddConstraint(
            model_name='ownershipevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'project', 'period'), name='unique_ownership_eval'),
        ),
        migrations.AddConstraint(
            model_name='ownershipevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('user', 'period'), name='unique_lead_ownership_eval'),
        ),
    ]
