# Generated by Django 6.0.6 on 2026-06-29 18:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_scenariooption'),
        ('evaluations', '0003_ownership_project_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTalentSessionNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fortalezas', models.TextField(blank=True, verbose_name='fortalezas Mesa de Talento')),
                ('oportunidades', models.TextField(blank=True, verbose_name='oportunidades Mesa de Talento')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='actualizado el')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='creado el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'historical nota de Mesa de Talento',
                'verbose_name_plural': 'historical notas de Mesa de Talento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TalentSessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortalezas', models.TextField(blank=True, verbose_name='fortalezas Mesa de Talento')),
                ('oportunidades', models.TextField(blank=True, verbose_name='oportunidades Mesa de Talento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_talent_notes', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talent_notes', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('scenario_actual', models.ManyToManyField(blank=True, related_name='notes_actual', to='catalog.scenariooption', verbose_name='escenario actual')),
                ('scenario_s1', models.ManyToManyField(blank=True, related_name='notes_s1', to='catalog.scenariooption', verbose_name='escenario S+1')),
                ('scenario_s2', models.ManyToManyField(blank=True, related_name='notes_s2', to='catalog.scenariooption', verbose_name='escenario S+2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_notes', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'nota de Mesa de Talento',
                'verbose_name_plural': 'notas de Mesa de Talento',
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='es principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_responsable_records', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='evaluations.talentsessionnote', verbose_name='nota')),
            ],
            options={
                'verbose_name': 'responsable de retroalimentación',
                'verbose_name_plural': 'responsables de retroalimentación',
            },
        ),
        migrations.AddConstraint(
            model_name='talentsessionnote',
            constraint=models.UniqueConstraint(fields=('user', 'period'), name='unique_talent_note'),
        ),
        migrations.AddConstraint(
            model_name='feedbackresponsible',
            constraint=models.UniqueConstraint(fields=('note', 'user'), name='unique_feedback_responsible'),
        ),
    ]
