# Generated by Django 6.0.6 on 2026-07-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_talent_session_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaluedeliveryevaluation',
            name='comments',
            field=models.TextField(blank=True, help_text='Notas de contexto sobre la Entrega de Valor. Las captura el responsable y puede complementarlas el Validador; se muestran también en la Mesa de Talento.', verbose_name='comentarios'),
        ),
        migrations.AddField(
            model_name='valuedeliveryevaluation',
            name='comments',
            field=models.TextField(blank=True, help_text='Notas de contexto sobre la Entrega de Valor. Las captura el responsable y puede complementarlas el Validador; se muestran también en la Mesa de Talento.', verbose_name='comentarios'),
        ),
        migrations.AlterField(
            model_name='historicalvaluedeliveryevaluation',
            name='validated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validado por'),
        ),
        migrations.AlterField(
            model_name='valuedeliveryevaluation',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vd_validations', to=settings.AUTH_USER_MODEL, verbose_name='validado por'),
        ),
    ]
