# Generated by Django 6.0.6 on 2026-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_historicalvaluedeliveryevaluation_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, verbose_name='comentarios adicionales de retroalimentación'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='expectativas_personales',
            field=models.TextField(blank=True, verbose_name='expectativas personales'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='expectativas_profesionales',
            field=models.TextField(blank=True, verbose_name='expectativas profesionales'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='objetivo_desarrollo_1',
            field=models.TextField(blank=True, verbose_name='objetivo de desarrollo 1'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='objetivo_desarrollo_2',
            field=models.TextField(blank=True, verbose_name='objetivo de desarrollo 2'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='objetivo_desarrollo_3',
            field=models.TextField(blank=True, verbose_name='objetivo de desarrollo 3'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, verbose_name='comentarios adicionales de retroalimentación'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='expectativas_personales',
            field=models.TextField(blank=True, verbose_name='expectativas personales'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='expectativas_profesionales',
            field=models.TextField(blank=True, verbose_name='expectativas profesionales'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='objetivo_desarrollo_1',
            field=models.TextField(blank=True, verbose_name='objetivo de desarrollo 1'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='objetivo_desarrollo_2',
            field=models.TextField(blank=True, verbose_name='objetivo de desarrollo 2'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='objetivo_desarrollo_3',
            field=models.TextField(blank=True, verbose_name='objetivo de desarrollo 3'),
        ),
    ]
