# Generated by Django 6.0.6 on 2026-07-02 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_historicaltalentsessionnote_comentarios_adicionales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='feedback_agreed',
            field=models.BooleanField(default=False, verbose_name='acordado con el colaborador'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='feedback_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acordado el'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='feedback_agreed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='acordado por'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='feedback_agreed',
            field=models.BooleanField(default=False, verbose_name='acordado con el colaborador'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='feedback_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acordado el'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='feedback_agreed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_sessions_agreed', to=settings.AUTH_USER_MODEL, verbose_name='acordado por'),
        ),
    ]
