# Generated by Django 6.0.6 on 2026-07-13 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_historicaltalentsessionnote_feedback_agreed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='mesa_ready',
            field=models.BooleanField(default=False, verbose_name='listo en Mesa de Talento'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='mesa_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='listo en Mesa el'),
        ),
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='mesa_ready_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='marcado listo por'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='mesa_ready',
            field=models.BooleanField(default=False, verbose_name='listo en Mesa de Talento'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='mesa_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='listo en Mesa el'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='mesa_ready_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesa_ready_notes', to=settings.AUTH_USER_MODEL, verbose_name='marcado listo por'),
        ),
    ]
