# Generated by Django 6.0.6 on 2026-07-14 00:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_historicalproject_validador_project_validador'),
        ('evaluations', '0008_historicaltalentsessionnote_mesa_ready_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMesaProjectReview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, verbose_name='revisado el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.project', verbose_name='proyecto')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'historical revisión de Mesa por proyecto',
                'verbose_name_plural': 'historical revisiones de Mesa por proyecto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MesaProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='revisado el')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesa_project_reviews', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesa_project_reviews', to='catalog.project', verbose_name='proyecto')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesa_reviews_done', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesa_project_reviews', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'revisión de Mesa por proyecto',
                'verbose_name_plural': 'revisiones de Mesa por proyecto',
                'constraints': [models.UniqueConstraint(fields=('period', 'user', 'project'), name='unique_mesa_project_review')],
            },
        ),
    ]
