# Generated by Django 6.0.6 on 2026-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_historicalmesaprojectreview_mesaprojectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='comentarios Mesa de Talento'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='comentarios Mesa de Talento'),
        ),
    ]
