# Generated by Django 6.0.7 on 2026-07-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_invert_scenario_option_order'),
        ('evaluations', '0010_historicaltalentsessionnote_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalentsessionnote',
            name='scenario_actual_tmp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.scenariooption', verbose_name='escenario actual (tmp)'),
        ),
        migrations.AddField(
            model_name='talentsessionnote',
            name='scenario_actual_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_actual_tmp', to='catalog.scenariooption', verbose_name='escenario actual (tmp)'),
        ),
    ]
