# Generated by Django 6.0.7 on 2026-07-28 02:30

from django.db import migrations


def _copy_forwards(apps, schema_editor):
    TalentSessionNote = apps.get_model("evaluations", "TalentSessionNote")
    for note in TalentSessionNote.objects.exclude(scenario_actual=None).prefetch_related("scenario_actual"):
        first = note.scenario_actual.first()
        if first is not None:
            note.scenario_actual_tmp_id = first.pk
            note.save(update_fields=["scenario_actual_tmp"])


def _copy_backwards(apps, schema_editor):
    TalentSessionNote = apps.get_model("evaluations", "TalentSessionNote")
    for note in TalentSessionNote.objects.exclude(scenario_actual_tmp=None):
        note.scenario_actual.set([note.scenario_actual_tmp_id])


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_scenario_actual_fk_step1_add_tmp'),
    ]

    operations = [
        migrations.RunPython(_copy_forwards, _copy_backwards),
    ]
