# Generated by Django 6.0.7 on 2026-07-28 02:31 (editado a mano: RenameField en
# vez de Remove+Add para no perder los datos ya copiados en el paso 2).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_invert_scenario_option_order'),
        ('evaluations', '0012_scenario_actual_fk_step2_copy_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltalentsessionnote',
            old_name='scenario_actual_tmp',
            new_name='scenario_actual',
        ),
        migrations.RemoveField(
            model_name='talentsessionnote',
            name='scenario_actual',
        ),
        migrations.RenameField(
            model_name='talentsessionnote',
            old_name='scenario_actual_tmp',
            new_name='scenario_actual',
        ),
        migrations.AlterField(
            model_name='talentsessionnote',
            name='scenario_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_actual', to='catalog.scenariooption', verbose_name='escenario actual'),
        ),
    ]
