# Generated by Django 6.0.7 on 2026-07-28 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_invert_scenario_option_order'),
        ('evaluations', '0013_scenario_actual_fk_step3_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltalentsessionnote',
            name='scenario_actual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.scenariooption', verbose_name='escenario actual'),
        ),
    ]
