# Generated by Django 6.0.7 on 2026-09-21 23:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_evaluationperiod_unique_open_period'),
        ('evaluations', '0014_alter_historicaltalentsessionnote_scenario_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFinalScore',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ownership_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('value_delivery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('arena_impact_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('band', models.CharField(blank=True, max_length=20, verbose_name='banda')),
                ('is_complete', models.BooleanField(default=False, verbose_name='completa')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='actualizada el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.evaluationperiod', verbose_name='periodo')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'historical calificación final',
                'verbose_name_plural': 'historical calificaciones finales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
