# Generated by Django 6.0.6 on 2026-06-10 15:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('text', models.TextField(blank=True, verbose_name='descripción')),
                ('qtype', models.CharField(choices=[('SCALE', 'Escala 1–4 / N/A'), ('TEXT_LONG', 'Texto largo')], default='SCALE', max_length=12, verbose_name='tipo')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='peso')),
                ('allow_na', models.BooleanField(default=True, verbose_name='permite N/A')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoria')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalQuestionnaireTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OWNERSHIP', 'Ownership'), ('VALUE_DELIVERY', 'Entrega de Valor')], max_length=16, verbose_name='tipo')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=12, verbose_name='estado')),
                ('scale_note', models.TextField(blank=True, help_text='Texto de la escala que se muestra al usuario.', verbose_name='nota de escala')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.area', verbose_name='área')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.senioritylevel', verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'historical cuestionario',
                'verbose_name_plural': 'historical cuestionarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OWNERSHIP', 'Ownership'), ('VALUE_DELIVERY', 'Entrega de Valor')], max_length=16, verbose_name='tipo')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=12, verbose_name='estado')),
                ('scale_note', models.TextField(blank=True, help_text='Texto de la escala que se muestra al usuario.', verbose_name='nota de escala')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='catalog.area', verbose_name='área')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='catalog.senioritylevel', verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'cuestionario',
                'verbose_name_plural': 'cuestionarios',
                'ordering': ['kind', 'area__code', 'level__order', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ScaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, help_text='1–4; vacío = N/A.', null=True, verbose_name='valor')),
                ('label', models.CharField(max_length=40, verbose_name='etiqueta')),
                ('description', models.TextField(blank=True, verbose_name='descriptor')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale_options', to='questionnaires.question', verbose_name='pregunta')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale_options', to='questionnaires.questionnairetemplate', verbose_name='cuestionario')),
            ],
            options={
                'verbose_name': 'opción de escala',
                'verbose_name_plural': 'opciones de escala',
                'ordering': ['template', 'question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='questionnaires.questionnairetemplate', verbose_name='cuestionario')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.section', verbose_name='sección'),
        ),
        migrations.AddConstraint(
            model_name='questionnairetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLICADO')), fields=('kind', 'area', 'level'), name='unique_published_template'),
        ),
        migrations.AddConstraint(
            model_name='questionnairetemplate',
            constraint=models.UniqueConstraint(fields=('kind', 'area', 'level', 'version'), name='unique_template_version'),
        ),
    ]
