# Generated by Django 6.0.6 on 2026-06-10 15:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nombre')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de cierre')),
                ('kind', models.CharField(choices=[('SEMESTRAL', 'Semestral'), ('TRIMESTRAL', 'Trimestral')], default='SEMESTRAL', max_length=12, verbose_name='tipo')),
                ('status', models.CharField(choices=[('PLANEADO', 'Planeado'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='PLANEADO', max_length=12, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'periodo',
                'verbose_name_plural': 'periodos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SeniorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'nivel de seniority',
                'verbose_name_plural': 'niveles de seniority',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvaluationPeriod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='nombre')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de cierre')),
                ('kind', models.CharField(choices=[('SEMESTRAL', 'Semestral'), ('TRIMESTRAL', 'Trimestral')], default='SEMESTRAL', max_length=12, verbose_name='tipo')),
                ('status', models.CharField(choices=[('PLANEADO', 'Planeado'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='PLANEADO', max_length=12, verbose_name='estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical periodo',
                'verbose_name_plural': 'historical periodos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='cliente')),
                ('duration_type', models.CharField(choices=[('FINITO', 'Tiempo finito (con fecha de entrega)'), ('INDEFINIDO', 'Servicio / iniciativa de tiempo indefinido')], default='FINITO', max_length=12, verbose_name='tipo de duración')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='líder de proyecto')),
            ],
            options={
                'verbose_name': 'historical proyecto',
                'verbose_name_plural': 'historical proyectos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='cliente')),
                ('duration_type', models.CharField(choices=[('FINITO', 'Tiempo finito (con fecha de entrega)'), ('INDEFINIDO', 'Servicio / iniciativa de tiempo indefinido')], default='FINITO', max_length=12, verbose_name='tipo de duración')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='líder de proyecto')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PillarWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_ownership', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='peso Ownership')),
                ('w_value_delivery', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='peso Entrega de Valor')),
                ('w_arena_impact', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='peso Impacto Arena')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='catalog.senioritylevel', verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'ponderación por nivel',
                'verbose_name_plural': 'ponderaciones por nivel',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPillarWeight',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('w_ownership', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='peso Ownership')),
                ('w_value_delivery', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='peso Entrega de Valor')),
                ('w_arena_impact', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='peso Impacto Arena')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.senioritylevel', verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'historical ponderación por nivel',
                'verbose_name_plural': 'historical ponderaciones por nivel',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='desde')),
                ('end', models.DateField(blank=True, null=True, verbose_name='hasta')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.project', verbose_name='proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
            ],
            options={
                'verbose_name': 'miembro de proyecto',
                'verbose_name_plural': 'miembros de proyecto',
                'ordering': ['project__name', 'user__full_name'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
