# Generated by Django 6.0.6 on 2026-06-12 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='kickoff',
            field=models.DateField(blank=True, null=True, verbose_name='kick-off'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(choices=[('ON_TRACK', 'On track'), ('DELAYED', 'Delayed')], default='ON_TRACK', max_length=10, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='target_close',
            field=models.DateField(blank=True, null=True, verbose_name='cierre objetivo'),
        ),
        migrations.AddField(
            model_name='project',
            name='kickoff',
            field=models.DateField(blank=True, null=True, verbose_name='kick-off'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ON_TRACK', 'On track'), ('DELAYED', 'Delayed')], default='ON_TRACK', max_length=10, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_close',
            field=models.DateField(blank=True, null=True, verbose_name='cierre objetivo'),
        ),
    ]
