# Generated by Django 6.0.6 on 2026-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_project_rename_lead_to_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'opción de escenario',
                'verbose_name_plural': 'opciones de escenario',
                'ordering': ['order'],
            },
        ),
    ]
