# Generated by Django 6.0.6 on 2026-06-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_scenariooption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariooption',
            name='code',
        ),
    ]
