# Generated by Django 6.0.6 on 2026-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_scenariooption_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariooption',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
