# Generated by Django 6.0.7 on 2026-07-28 01:55
import re

from django.db import migrations

# Mapea el order actual (1..5, 1=mejor) al nuevo order (1..5, 5=mejor):
# new_order = 6 - old_order. Se aplica solo a los 5 escenarios sembrados
# manualmente en 2026-06; si el catálogo ya no tiene exactamente esas 5
# filas (entorno de pruebas, catálogo editado a mano), no se toca nada.
_PREFIX_RE = re.compile(r"^\s*(\d+)\.\s*(.*)$")


def _invert(apps, schema_editor):
    ScenarioOption = apps.get_model("catalog", "ScenarioOption")
    options = list(ScenarioOption.objects.all())
    if len(options) != 5 or sorted(o.order for o in options) != [1, 2, 3, 4, 5]:
        return
    for opt in options:
        new_order = 6 - opt.order
        match = _PREFIX_RE.match(opt.name)
        if match:
            opt.name = f"{new_order}. {match.group(2)}"
        opt.order = new_order
        opt.save(update_fields=["name", "order"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_historicalproject_validador_project_validador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariooption',
            options={'ordering': ['-order'], 'verbose_name': 'opción de escenario', 'verbose_name_plural': 'opciones de escenario'},
        ),
        migrations.RunPython(_invert, _invert),
    ]
