# Generated by Django 6.0.7 on 2026-09-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_invert_scenario_option_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evaluationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABIERTO')), fields=('status',), name='unique_open_period'),
        ),
    ]
