# Generated by Django 6.0.6 on 2026-10-07 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_evaluationperiod_unique_open_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DIRECTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_areas', to=settings.AUTH_USER_MODEL, verbose_name='director'),
        ),
    ]
