# Generated by Django 6.0.6 on 2026-10-08 03:45

import apps.access.registry
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descripción')),
                ('is_system', models.BooleanField(default=False, help_text='Superusuario: no se edita ni se asigna desde la UI.', verbose_name='de sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROFILE_CREATED', 'Perfil creado'), ('PROFILE_RENAMED', 'Perfil editado'), ('PROFILE_DELETED', 'Perfil eliminado'), ('GRANT_CHANGED', 'Permiso cambiado'), ('PROFILE_ASSIGNED', 'Perfil asignado')], max_length=20)),
                ('profile_name', models.CharField(blank=True, max_length=80)),
                ('permission_key', models.CharField(blank=True, max_length=80)),
                ('old_value', models.CharField(blank=True, max_length=80)),
                ('new_value', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de permisos',
                'verbose_name_plural': 'bitácora de permisos',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProfileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=80, verbose_name='permiso')),
                ('scope', models.PositiveSmallIntegerField(default=apps.access.registry.Scope['NINGUNO'], verbose_name='alcance')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.profile')),
            ],
            options={
                'verbose_name': 'concesión',
                'verbose_name_plural': 'concesiones',
                'constraints': [models.UniqueConstraint(fields=('profile', 'permission_key'), name='uniq_profile_permission')],
            },
        ),
    ]
